### ISSUE TITLE
Animate when position changes

### ISSUE THREAD

**Issue by geovannimp** [madewithfelt/flutter_layout_grid#15]
Hi, I'm new to flutter and would like to have an animation when withGridPlacement changes position.

Is this possible with this library?

**Comment by shyndman** [comment]
Hey @geovannimp,

Sorry this took me so long. I've finally got time to work on this again.

The answer is no, that isn't currently possible...but from a technical standpoint it could be done. 

Do you have an example of an effect similar to the one you're looking for, so I can get a feel for it?

**Comment by geovannimp** [comment]
I don't actually remember anymore what I was trying to do, I think was reorganize the grid with drag and drop with itens that could change size. 
I ended using a fadein/fadeout animation and placing two grids over each other to simulate the transition animation.

![Peek 13-09-2020 20-49](https://user-images.githubusercontent.com/4943174/104372615-ccd6fd00-54fe-11eb-930c-1b6768496ab5.gif)

**Comment by shyndman** [comment]
Awesome. Looks really good.

I'm going to close this off for now, but I'll keep it in mind in case someone else has the same ask.
