### ISSUE TITLE
Null safety release

### ISSUE THREAD

**Issue by Skyost** [madewithfelt/flutter_layout_grid#17]
Hey,

As more and more packages are getting compatible with null safety, would it be possible for you to make a null safety release ? I need it personally because my app uses `flutter_math` which relies on `quiver: ^3.0.0-nullsafety` and it also use your package which relies on `quiver ^2.0.0`.

Thanks !

**Comment by shyndman** [comment]
Definitely. I'll see what I can do today.

**Comment by Skyost** [comment]
Great !

**Comment by shyndman** [comment]
I made a lot of progress, but still not quite there. Unless something surprising comes up, this will be ready and published by EOD tomorrow.

**Comment by Skyost** [comment]
Cool, is there a branch or a pull request where we can track the progress @shyndman ?

**Comment by shyndman** [comment]
There you are.

**Comment by shyndman** [comment]
All errors worked through, and tests are passing.

This is my first Dart null-safety experience. Not bad at all. :)

**Comment by shyndman** [comment]
OK, published as `0.11.0-nullsafety.0`. Give it a shot.

**Comment by Skyost** [comment]
I'm gonna try it tomorrow. Thanks a lot :wink:

**Comment by shyndman** [comment]
You're welcome. Thanks for using the package. :)

**Comment by shyndman** [comment]
OK, so I got that code sample you gave me running, confirmed that it's not working properly, and I think I see what's happening.

Thinking through what the correct behavior should be now.
