### ISSUE TITLE
Needs migration to use computeDryLayout

### ISSUE THREAD

**Issue by erickok** [madewithfelt/flutter_layout_grid#42]
As of the next upcoming Flutter stable release, RenderBox implementations are required to implement a new `computeDryLayout` function. This should calculate and return its (intrinsic) size. As the library currently doesn't implement `performResize`, the appropriate sizing code should be extracted from `performLayout`. I took a quick look but am not quite confident in the rendering code to make the change, and am sure it will be trivial for you.

See the official migration guide at https://flutter.dev/docs/release/breaking-changes/renderbox-dry-layout#migration-guide

This will become a blocking issue once Flutter 1.26 has been released to stable.

**Comment by shyndman** [comment]
I read over the docs, and I think this might be super simple (`computeDrySize` calls `RenderLayoutGrid.computeGridSize`, I think?)

Weird that I didn't get an email about this though. I used to. Let me look into that too.

Thanks for the heads up.

**Comment by shyndman** [comment]
This appears to work, but I have an outstanding question for the Flutter team on whether I'm allowed to be doing something.

**Comment by shyndman** [comment]
Available in 1.0.0-nullsafety.0
