### ISSUE TITLE
Cut new releases to satisfy non-null-safe and null-safe versions of the library

### ISSUE THREAD

**Issue by shyndman** [madewithfelt/flutter_layout_grid#44]
The recommended null-safety migration strategy for pre-1.0 libraries is to bump the minor version, and build from there. Which I did, but I now have breaking API changes for the non-null-safe library which I'd like to release, and I can no longer do that safely (because non-null-safe is 0.10.x which I can't bump to 0.11.x because the null-safe release is already there).

To solve this, I am going to temporarily break semver, but I won't ever have to again. Here are the versions that I'll be releasing simultaneously:

#### `0.11.0`
* Includes #35, tons of bug fixes, some API changes, and new examples
* This will allow me full freedom to continue iterating on the non-null-safe version
* Breaks semver, as I'll be releasing a non-null-safe release following a null-safe prerelease

#### `1.0.0-nullsafety.0`
* Includes all of the above plus #43 and #18
* Ready to go for Flutter 1.25

Thoughts @Skyost and @erickok? @mikebutlin?

**Comment by erickok** [comment]
This is reasonable and understandable and I don't think you'll step on anyone's toes. I'd go for it. You are extremely well in (self-)documenting the project so I don't think you will confuse any existing lib consumer.

**Comment by shyndman** [comment]
This is done.

Note that for the `1.0.0-nullsafety.1` release, I renamed two `LayoutGrid` parameters

* `templateRowSizes` is now `rowSizes`
* `templateColumnSizes` is now `columnSizes`
