### ISSUE TITLE
Share auto rowSizes/columnSizes between two LayoutGrids?

### ISSUE THREAD

**Issue by sabetAI** [madewithfelt/flutter_layout_grid#56]
I have two `LayoutGrid` objects with `auto` `rowSizes`. Is there a way to share these `rowSizes` while keeping them `auto`?

**Comment by shyndman** [comment]
Hi @sabetAI,

There might be...can you explain what you're trying to do a bit more?

**Comment by sabetAI** [comment]
I'm embedding `LayoutGrid`s inside of a `LayoutGrid`. The nested grids are a legend, header, margin, and body (labelled in the first image). I have the header and margin grids pinned in place, while the body grid is fully scrollable, with the scrollControllers of the margin and header synced with the body's vertical and horizontal scrollers respectively. This lets me scroll anywhere in the table while keeping the header/margin cells in view. The issue is that adjacent cells between the margin and body grids don't line up (visible in first image), because I have their `rowSizes` set as `auto` to adjust according to content size. 

<img src="https://user-images.githubusercontent.com/28828395/108923143-4c7bdf80-7606-11eb-89a1-5216af1ed81a.png" width="25%" height="25%">

I can fix the `rowSizes` for the margin and body grids, but any heuristic I use might not cover all cases ie parts of text are cut off in some cells.

<img src="https://user-images.githubusercontent.com/28828395/108920834-5ea84e80-7603-11eb-8776-ff1632d16f39.png" width="25%" height="25%">

Any suggestions would help!

**Comment by sabetAI** [comment]
This is what it looks like in practice: 

<img src="https://user-images.githubusercontent.com/28828395/108925525-ca41ea00-760a-11eb-9572-989cd3bdab20.gif" width="25%" height="25%">

Notice the margin `rowSizes` are slightly misaligned with the body's, and the vertical scroller goes a little out of sync at the end due to the different `auto` `rowSizes`.

**Comment by shyndman** [comment]
I understand. Looks great (I love seeing how this stuff is used).

I can think of two options that would work...neither very satisfying, but it would get you going. Let me know what you think, and whether you need any help getting it going.

#### Data duplication between grids

Duplicate the body's data in the margin, and/or the margin's data in the body, in hidden cells. The grid library allows grid items to overlap each other, so you can have multiple cells contributing to the height of a row, all in one column.

Super ugly, I know. But, an option.

#### Use sizing information from `RenderLayoutGrid`

The `RenderObject` responsible for laying out a `LayoutGrid`, `RenderLayoutGrid`, exposes all the sizing information from its previous layout in the `lastGridSizing` field. This includes row starts, heights, gaps, you name it. It isn't currently a public field, but it could be (it's currently `@visibleForTesting`, so it's public enough that you could try this out)

I can imagine a solution where you render the rows from both grids with `auto`, grab the computed row sizes from each `RenderLayoutGrid`, and then replace those `auto` rows with fixed ones with a height of `max(marginRowHeights[i], bodyRowHeights[i])`.

Not as ugly as the approach above, but requires some doing. It would run considerably more quickly as well.

#### Future approach?

This looks like the kind of thing that could be solved using an implementation of [CSS's `subgrid`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid)...maybe something I should think about writing.

**Comment by shyndman** [comment]
How do you decide how many rows are spanned by the margin labels?

**Comment by shyndman** [comment]
Really interesting use case, btw. It's got me thinking.

**Comment by sabetAI** [comment]
Thanks for the suggestions @shyndman! I found `flutter_layout_grid` to be the most elegant way to implement my table, it's worked out pretty great so far! 

The rowspans for the margin labels are known a-priori, since I'm stripping the content from an html table. I'll try your second suggestion first, and get sizing info from `RenderLayoutGrid`. I'll let you know how it goes.

**Comment by shyndman** [comment]
Please do. Happy to help any way I can.

**Comment by sabetAI** [comment]
Hi @shyndman, I tried implementing your suggestion as follows:

```
final tableRender = tableLayout.createRenderObject(context);
final lastGridSizing = tableRender.lastGridSizing;
```

I tried inserting this snippet into my `build` method, and alternatively as a post-build callback with
`WidgetsBinding.instance.addPostFrameCallback((_) => getRender(context));` (from [stackoverflow](https://stackoverflow.com/a/54553143/12666076)).

In both cases, the `lastGridSizing` field is `null`. Any thoughts on why this might be the case?

**Comment by shyndman** [comment]
The post-build callback is definitely the way you want to go, because you want to reuse the work the grid has already done.

In your snippet, what does `getRender` do?

**Comment by sabetAI** [comment]
Doesn't do anything yet, I just use it as a breakpoint to inspect the `lastGridSizing` field:
```
getRender(BuildContext context) {
  final tableRender = tableLayout.createRenderObject(context);
  final lastGridSizing = tableRender.lastGridSizing;
}
```
`lastGridSizing` is always `null` though unfortunately..

**Comment by shyndman** [comment]
Gotcha.

OK, so this line : `final tableRender = tableLayout.createRenderObject(context);` is creating a brand new `RenderLayoutGrid`, and it hasn't been laid out yet, so doesn't have grid sizing.

What you're going to want to do instead is retrieve an existing `RenderLayoutGrid`. Give me a few and I'll show you what that looks like.

**Comment by shyndman** [comment]
https://gist.github.com/shyndman/4b52b4f5bcb2e4ba340adef6e69c8bc3

**Comment by sabetAI** [comment]
Ahh okay using a `GlobalKey` to access the `RenderLayoutGrid` through `findRenderObject()` makes a lot of sense. I assume I have to create new `LayoutGrid` objects and re-build the widget again afterwards, right? I'll try it out, thanks!

**Comment by shyndman** [comment]
(Keep me posted — I'm going to be working for a few more hours)

**Comment by shyndman** [comment]
Yeah, exactly. I imagine that you'd call `setState()` from inside your post-frame callback, once you've calculated all the sizes and stored them in a field.

The `setState` will trigger a widget rebuild, you'd supply the fixed sizes instead of `auto`s to the grids...and that's it.

I acknowledge that this should be easier. I don't think your use case is too unusual.

**Comment by sabetAI** [comment]
Works perfectly now!

![workingTable](https://user-images.githubusercontent.com/28828395/108947359-4f8ac600-762e-11eb-87cf-0a0732ec993c.gif)

Ideally, sharing the `rowSizes` through the constructor (or by some other means) would avoid having to build the LayoutGrid twice, but this workaround definitely gets the job done!

**Comment by shyndman** [comment]
Amazing!

> Ideally, some option of sharing rowSizes would avoid having to build the LayoutGrid twice, but this workaround definitely gets the job done!

I think I see what you're getting at, but can you expand on this?

**Comment by shyndman** [comment]
Something like this?

```dart
void build(context) {
  final sharedRowSizes = [auto, auto, auto];
 
  return Row(
    children: [
      // margin grid
      LayoutGrid(rowSizes: sharedRowSizes),
      // body grid
      LayoutGrid(rowSizes: sharedRowSizes),
    ],
  );
}
```

**Comment by sabetAI** [comment]
> Something like this?
> 
> ```dart
> void build(context) {
>   final sharedRowSizes = [auto, auto, auto];
>  
>   return Row(
>     children: [
>       // margin grid
>       LayoutGrid(rowSizes: sharedRowSizes),
>       // body grid
>       LayoutGrid(rowSizes: sharedRowSizes),
>     ],
>   );
> }
> ```
> 
> and by doing this, the grids would calculate a set of shared row heights?

Exactly, though I suppose that would require a lot of 'magic' to happen under the hood. Packages like [linked_scroll_controller](https://pub.dev/packages/linked_scroll_controller) create a "group" object and add controllers to it, maybe creating LayoutGrid parameter groups to sync them together is an option? Hard for me to say what the simplest solution is.

**Comment by shyndman** [comment]
I have to think about it, but they're interesting suggestions — different directions than I was thinking, but possibly better.

I'm going to leave this issue open until I can break this out into something concrete.
