### ISSUE TITLE
Resizable elements?

### ISSUE THREAD

**Issue by polyrain** [madewithfelt/flutter_layout_grid#61]
Hi,

I'm pretty new to flutter and was wondering if there was any support/it might be on a roadmap to permit resizable elements? Im trying to create kind of a drag and drop system where the user can shrink the item and then move it around, with the rest of the grid repacking to accommodate. Is this doable?

**Comment by shyndman** [comment]
Hi @polyrain,

Could you go into some more detail? 

Would this drag and drop be moving items between cells? 

Can you describe what you mean by resizing elements in terms of how the grid is constructed, the interactions performed by the user, and the desired effect?

**Comment by shyndman** [comment]
Like...a detailed use case. Because in my mind, this is already possible. Just needs the deets. :)

**Comment by polyrain** [comment]
> Hi @polyrain,
> 
> Could you go into some more detail? 

Hey! Yep sure, sorry for the vagueness in my initial issue.

> Would this drag and drop be moving items between cells? 

Yes. Im trying to make a thing where people can change element size based on how important they are/how long it will take and then they can move it around on a grid to visualise their tasks.

> Can you describe what you mean by resizing elements in terms of how the grid is constructed, the interactions performed by the user, and the desired effect?

As a user, I am presented with an initially unfilled grid of fixed size (let's say 9 cells, 3x3). I can add a new element to a cell by tapping a cell. That element fills 1 cell. (One use case)

As a user, I can also tap elements to see information about them. After tapping a cell, and having it be 'selected', I can change its size from occupying one cell to occupying say 1x2 or 2x1, or however large I want it. If other elements are already in cells, that's an invalid change to size. (Two use case)

Finally, I can tap and hold an element to drag it around the grid and move it into an unoccupied area of the grid that is free. So I could move an element from 0,0 on our grid, to 3,3 by dragging it, assuming it's size is still 1x1. (Three use case)

Does that clarify the sort of functionality I'm unsure about? I know the grid currently can't support auto scaling (like growing arbitrarily based on just adding new items, but can if you construct a new grid and stuff) based on the README, but yeah I think the package is really cool and just wanna get a better idea if it can suit my needs. 

Thank you so much for your quick reply :)

**Comment by shyndman** [comment]
Everything you described should be possible.

Want me to summarize how it could be constructed?

**Comment by shyndman** [comment]
And qq: by fixed size, I understand you to mean that the number of rows and columns are fixed. Is it also fixed size in terms of its on-screen dimensions? (500px x 500 px, or whatever)

**Comment by shyndman** [comment]
Another qq: Where does repacking come into it?

**Comment by polyrain** [comment]
> And qq: by fixed size, I understand you to mean that the number of rows and columns are fixed. Is it also fixed size in terms of its on-screen dimensions? (500px x 500 px, or whatever)

Yeah, sorry; I did mean rows and columns are fixed, I don't think a constraint on the overall screen dimensions is a constraint I would envision, mainly as I can see it being desired to have the on screen dimensions be zoomable or such.

I'd actually really love a quick rundown of how it could be possible; high level, of course, but if you did have time that would be incredible; I didn't expect this level of detail in your replies, but I am really appreciative!

**Comment by polyrain** [comment]
> Another qq: Where does repacking come into it?

I'm interpreting this as rebuilding the grid, correct me if I'm wrong, but the actual visual area would be repacked whenever a user has stopped providing input on dragging and dropping for example and (assuming no overlapping elements on the potential new grid region) the element has been 'moved' to the new position. Elements on the grid don't need to dynamically shift as the user is dragging elements, so the only repacking happens at the very end.

**Comment by shyndman** [comment]
Gotcha.

So I think the big thing here is having a model that describes the elements that have been created, along with their positions, and colspans/rowspans. Which you probably already have.

You'll want to set it up so model changes trigger grid rebuilds. Maybe this is done through a `setState()` on a `StatefulWidget`'s `State`, or by using an `InheritedWidget`, or something from the [`provider`](https://pub.dev/packages/provider) package...doesn't matter. 

The second piece to this are the utility widgets. You'll want to represent empty cells with something that's selectable (which updates your model), so your user can insert, and can also act as a `DragTarget` for repositioning.

For your non-empty cells, your elements, I'd wrap the element's visual widget in a utility widget that uses `Draggable` for dynamic placement, and also hooks into taps for selection.

Devil's in the details, but I think that's the meat of it.

If you need a barebones drag and drop sample, I can also supply that. Seems like it would be a useful addition to the package's examples.

**Re: dynamic repacking:** I wouldn't bother. Sounds like you want a system where the user is in control of placement. If not, I can help with that too.

**Re: detail:** You're welcome. :)

**Comment by shyndman** [comment]
Tangentially (and you may not need this), it's worth noting that if a grid item changes its width/height, the grid is aware of it, and will re-layout/re-render to accommodate. This is particularly useful for `auto`-sized rows and columns.

**Comment by polyrain** [comment]
> Gotcha.
> 
> So I think the big thing here is having a model that describes the elements that have been created, along with their positions, and colspans/rowspans. Which you probably already have.
> 
> You'll want to set it up so model changes trigger grid rebuilds. Maybe this is done through a `setState()` on a `StatefulWidget`'s `State`, or by using an `InheritedWidget`, or something from the [`provider`](https://pub.dev/packages/provider) package...doesn't matter.
> 
> The second piece to this are the utility widgets. You'll want to represent empty cells with something that's selectable (which updates your model), so your user can insert, and can also act as a `DragTarget` for repositioning.
> 
> For your non-empty cells, your elements, I'd wrap the element's visual widget in a utility widget that uses `Draggable` for dynamic placement, and also hooks into taps for selection.
> 
> Devil's in the details, but I think that's the meat of it.

Thank you so much for this response; this looks like a really solid launching off point (and also confirms a bit of what I've been experimenting with over the last few days). I think I can see where this is all comes together, and allays my anxiety about going down the  wrong path in my design.

> If you need a barebones drag and drop sample, I can also supply that. Seems like it would be a useful addition to the package's examples.

I think this would be useful for the reasons you stated; I'd definitely get some use out of it as well!

> **Re: dynamic repacking:** I wouldn't bother. Sounds like you want a system where the user is in control of placement. If not, I can help with that too.

I think you're right in that my requirements don't exactly need it; maybe one day :)

**Comment by polyrain** [comment]
> Tangentially (and you may not need this), it's worth noting that if a grid item changes its width/height, the grid is aware of it, and will re-layout/re-render to accommodate. This is particularly useful for `auto`-sized rows and columns.

I wasn't aware of this, but this sounds very useful, insofar as increasing the size of elements in-place without changing their relative cell position seems like something that would be nice for users to have (i.e. they can opt for a more 'dynamic' (read: auto-sized cols/rows) experience that lets them increase size in place without needing to overflow into other cells). 

Is there a community for @madewithfelt stuff, or are GH Issues the main communication channels? I'd love to follow up at some point in future once I have things a little more concrete re: this whole discussion :)

**Comment by shyndman** [comment]
There wasn't, but there is now. https://discord.gg/6aQQ5t3x

I'll put this in the README for others in a bit. And yeah, I'd love to hear about how things go.

**Comment by shyndman** [comment]
and I'll post back about that example. :)

**Comment by shyndman** [comment]
Oh, and I'm going to close this off. Cool?

**Comment by polyrain** [comment]
Yep!
