### ISSUE TITLE
Is it possible to center all elements of a LayoutGrid?

### ISSUE THREAD

**Issue by CaptainDario** [madewithfelt/flutter_layout_grid#67]
Hi,
thanks for this great plugin I really like it for developing responsive UI's.
I am wondering if there is an option to center all elements of the grid (except for wrapping every widget in a `Center`).
Something like `MainAxisAlignment: MainAxisAlignment.center`

**Comment by shyndman** [comment]
That's great to hear. Thank you. :)

No, there isn't. My goal is to keep this package tightly focused on a single purpose, and I think this particular problem can be solved in a number of ways by the user (like as you said, using the `Center` widget).

Sorry about that.
