### ISSUE TITLE
What is the equivalent of childAspectRatio in LayoutGrid?

### ISSUE THREAD

**Issue by w568w** [madewithfelt/flutter_layout_grid#69]
Since `GridView` doesn't support some advanced features like varied spans, I take `flutter_layout_grid` as a perfect candidate of it.

But it seems necessary to pass a definite `rowSize`(i.e. defined with `.px`) to `LayoutGrid`, otherwise the height of the grid is always zero. What I expect is a parameter like `childAspectRatio` in `GridView` to set the h/w ratio of every child in the grid. I've tried to wrap the child with `AspectRatio` widget, but it doesn't work.

Here is a minimal example:
```dart
table = LayoutGrid(
  columnSizes: List.filled(cols, 1.fr),
  rowSizes: List.filled(rows, auto),
  children: _buildTable(cols, rows),
);

List<Widget> _buildTable(int cols, int rows) {
  List<Widget> result = List.generate(
      cols * rows,
      (index) => AspectRatio(
        aspectRatio: 9.0/16.0,
        child: Container(
              margin: EdgeInsets.all(2),
              padding: EdgeInsets.all(2),
              decoration: BoxDecoration(
                  color: Theme.of(context).hintColor.withOpacity(0.14),
                  borderRadius: BorderRadius.circular(4)),
            ).withGridPlacement(
                rowStart: index ~/ cols, columnStart: index % cols),
      ));
  return result;
}
```

It's rendered as a zero-height widget. How could I fix it?

**Comment by shyndman** [comment]
Hey, sorry. Got caught up. Looking now.

**Comment by w568w** [comment]
> I had to modify yours a bit, because .withGridPlacement was being applied to the wrong widget

Thanks! I found that is the problem. Now It works fine.
