### ISSUE TITLE
The library doesn't work in Flutter 1.14.0+

### ISSUE THREAD

**Issue by perfoWorks** [madewithfelt/flutter_layout_grid#8]
I have copied and paste example code provided in readme section and it doesn't work. Actually I had to completely remove this package to get my app back in working condition. 

Compiler message:
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_layout_grid-0.9.1/lib/src/widgets/placement.dart:25:7: Error: The non-abstract class 'GridPlacement' is missing implementations for these members:
 - ParentDataWidget.debugTypicalAncestorWidgetClass
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class GridPlacement extends ParentDataWidget<LayoutGrid> {
      ^^^^^^^^^^^^^
../../tools/flutter/packages/flutter/lib/src/widgets/framework.dart:1497:12: Context: 'ParentDataWidget.debugTypicalAncestorWidgetClass' is defined here.
  Type get debugTypicalAncestorWidgetClass;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_layout_grid-0.9.1/lib/src/widgets/placement.dart:25:7: Error: Type argument 'LayoutGrid' doesn't conform to the bound 'ParentData' of the type variable 'T' on 'ParentDataWidget' in the supertype 'ParentDataWidget' of class 'GridPlacement'.
 - 'LayoutGrid' is from 'package:flutter_layout_grid/src/widgets/layout_grid.dart' ('../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_layout_grid-0.9.1/lib/src/widgets/layout_grid.dart').
 - 'ParentData' is from 'package:flutter/src/rendering/object.dart' ('../../tools/flutter/packages/flutter/lib/src/rendering/object.dart').
Try changing type arguments so that they conform to the bounds.
class GridPlacement extends ParentDataWidget<LayoutGrid> {
      ^
../../tools/flutter/packages/flutter/lib/src/widgets/framework.dart:1468:33: Context: This is the type variable whose bound isn't conformed to.
abstract class ParentDataWidget<T extends ParentData> extends ProxyWidget {
                                ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.

**Comment by shyndman** [comment]
Hi @perfoWorks,

Flutter introduced a breaking change in v1.14.0. I have a fix in version `0.10.0-dev.0` of the library, so update your pubspec and you'll be good to go.

I'll be promoting version `0.10.0`  to stable once Flutter v1.14.0 is the in the stable channel.

**Comment by perfoWorks** [comment]
Thanks... Works like a charm now
